server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: quotation

  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:postgres}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:test123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

environment:
  jwt:
    secret-key: "8kTcEnj4ABscsjcWVOg06brYjyOwwVwdMB7s1BGwzBQDhmASi"
    # 토큰 만료 시간 (1시간)
    access-token-expiration-time: 3600000
    # 토큰 만료 시간 (30일)
    refresh-token-expiration-time: 2592000000
    # 토큰 만료 시간 (5분)
    password-refresh-token-expiration-time: 300000

one-signal:
  api-key: ${ONESIGNAL_API_KEY}
  app-id: ${ONESIGNAL_APP_ID}
