server:
  port: 8888

spring:
  application:
    name: quotation

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

