server:
  port: 8888

spring:
  application:
    name: quotation

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

environment:
  jwt:
    secret-key: "8kTcEnj4ABscsjcWVOg06brYjyOwwVwdMB7s1BGwzBQDhmASi"
    # 토큰 만료 시간 (1시간)
    access-token-expiration-time: 3600000
    # 토큰 만료 시간 (1주일)
    refresh-token-expiration-time: 604800000