name: Build Test

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build With Test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --parallel